# makefile for final

CC=g++

# cleans up directory
clean:
	rm -rf *.o
	rm -rf Final


# makes the executable files
Final: Computer.cpp Desktop.cpp Laptop.cpp Final.cpp
	$(CC) -o Final Computer.cpp Desktop.cpp Laptop.cpp Final.cpp